{
	"version": 1736511926,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/emoji-sheet0.png",
		"images/emoji-sheet1.png",
		"images/emoji-sheet2.png",
		"images/emoji-sheet3.png",
		"images/diddyoil-sheet0.png",
		"images/particles.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/pop (1).m4a",
		"media/pop (1).ogg",
		"media/boo.m4a",
		"media/boo.ogg",
		"media/laugh win.m4a",
		"media/laugh win.ogg",
		"media/sad meme.m4a",
		"media/sad meme.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}